// Maps Elite Prospects nationality names to FlagCDN country codes.
// FlagCDN URLs use lowercase codes, handled in ProspectCard with .toLowerCase().

export function getCountryCode(nationality) {
  const countries = {
    USA: "US",
    Canada: "CA",
    Sweden: "SE",
    Russia: "RU",
    Switzerland: "CH",
    Germany: "DE",
    Czechia: "CZ",
    Finland: "FI",
    France: "FR",
    Slovakia: "SK",
    Bangladesh: "BD",
    Bermuda: "BM",
    Kenya: "KE",
    Monaco: "MC",

    Cuba: "CU",

    Ecuador: "EC",
    "Costa Rica": "CR",
    Namibia: "NA",
    Paraguay: "PY",

    Cambodia: "KH",

    // UK / home nations
    England: "GB-ENG",
    Scotland: "GB-SCT",
    Wales: "GB-WLS",
    "Northern Ireland": "GB-NIR",
    "U.K.": "GB",

    Norway: "NO",
    Italy: "IT",
    Austria: "AT",
    Latvia: "LV",
    Netherlands: "NL",
    Hungary: "HU",
    Kazakhstan: "KZ",
    Belarus: "BY",
    Poland: "PL",
    Romania: "RO",
    Denmark: "DK",
    Spain: "ES",
    Australia: "AU",
    Ukraine: "UA",
    Belgium: "BE",
    Turkey: "TR",
    Slovenia: "SI",
    Israel: "IL",
    Lithuania: "LT",
    Iceland: "IS",
    "New Zealand": "NZ",
    Estonia: "EE",
    Kuwait: "KW",
    Bulgaria: "BG",
    Iran: "IR",
    Mexico: "MX",
    China: "CN",
    Croatia: "HR",
    India: "IN",
    Serbia: "RS",
    Japan: "JP",
    "South Korea": "KR",
    Mongolia: "MN",
    "Hong Kong": "HK",
    "South Africa": "ZA",
    Luxembourg: "LU",
    UAE: "AE",
    "Chinese Taipei": "TW",
    Bosnia: "BA",
    Thailand: "TH",
    Uzbekistan: "UZ",
    Singapore: "SG",
    Turkmenistan: "TM",
    Kyrgyzstan: "KG",

    // Elite has this misspelled in your data.
    Phillipines: "PH",
    Philippines: "PH",

    Greece: "GR",
    Indonesia: "ID",
    Malaysia: "MY",
    Colombia: "CO",
    Argentina: "AR",
    Armenia: "AM",
    Portugal: "PT",
    Ireland: "IE",
    "Åland Islands": "AX",
    "Puerto Rico": "PR",
    Andorra: "AD",
    Liechtenstein: "LI",
    Pakistan: "PK",
    Chile: "CL",
    Algeria: "DZ",
    Lebanon: "LB",
    Bahrain: "BH",
    "North Korea": "KP",
    Egypt: "EG",
    Brazil: "BR",
    "Cayman Islands": "KY",

    // Elite uses older/common hockey naming.
    Macedonia: "MK",

    Moldova: "MD",
    "Saudi Arabia": "SA",
    Tunisia: "TN",
    Jamaica: "JM",
    Cyprus: "CY",
    Morocco: "MA",
    Uganda: "UG",
    Haiti: "HT",
    Macau: "MO",
    "The Democratic Republic of Congo": "CD",
    Georgia: "GE",
    Vietnam: "VN",
    Zimbabwe: "ZW",
    Peru: "PE",
    Venezuela: "VE",

    // alternates
    // Common alternate names
    "Bosnia and Herzegovina": "BA",
    "Congo DR": "CD",
    "DR Congo": "CD",
    "Republic of Korea": "KR",
    "Korea, South": "KR",
    "Korea, North": "KP",
    "Czech Republic": "CZ",

    Taiwan: "TW",
  };

  return countries[nationality?.trim()] || null;
}
